//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LogParser.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LogParser.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Installed.
        /// </summary>
        public static string EliteInsightsNotInstalled {
            get {
                return ResourceManager.GetString("EliteInsightsNotInstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select some Logs from the List above..
        /// </summary>
        public static string Err_SelectLogs {
            get {
                return ResourceManager.GetString("Err_SelectLogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please set a Webhook URL first in the Settings..
        /// </summary>
        public static string Err_Webhook {
            get {
                return ResourceManager.GetString("Err_Webhook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install Elite Insights.
        /// </summary>
        public static string InstallEliteInsights {
            get {
                return ResourceManager.GetString("InstallEliteInsights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully installed Elite Insights!.
        /// </summary>
        public static string SuccessInstalled {
            get {
                return ResourceManager.GetString("SuccessInstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully updated Elite Insights!.
        /// </summary>
        public static string SuccessUpdate {
            get {
                return ResourceManager.GetString("SuccessUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Elite Insights.
        /// </summary>
        public static string UpdateEliteInsights {
            get {
                return ResourceManager.GetString("UpdateEliteInsights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload logs to Dps Report.
        /// </summary>
        public static string UploadToDpsReport {
            get {
                return ResourceManager.GetString("UploadToDpsReport", resourceCulture);
            }
        }
    }
}
